/**
 * reportExport.js
 * PDF and Excel export functions for Monthly Financial Reports.
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas/dist/html2canvas.esm.js';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

// ─── Helpers ─────────────────────────────────────────────────────────────────

const INR = (amount) =>
  `Rs. ${Number(amount).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;




// ─── Color palette ───────────────────────────────────────────────────────────

const COLORS = {
  bg: [10, 10, 15],
  card: [19, 19, 26],
  elevated: [28, 28, 39],
  purple: [124, 58, 237],
  blue: [59, 130, 246],
  green: [16, 185, 129],
  red: [239, 68, 68],
  yellow: [245, 158, 11],
  textPrimary: [248, 250, 252],
  textMuted: [148, 163, 184],
  textDisabled: [71, 85, 105],
  border: [45, 45, 69],
  white: [255, 255, 255],
};

// Draw a rounded rectangle (polyfill for jsPDF)
const roundedRect = (doc, x, y, w, h, r, fillColor, strokeColor) => {
  if (fillColor) doc.setFillColor(...fillColor);
  if (strokeColor) doc.setDrawColor(...strokeColor);
  doc.roundedRect(x, y, w, h, r, r, fillColor && strokeColor ? 'FD' : fillColor ? 'F' : 'D');
};

// ─── PDF EXPORT ───────────────────────────────────────────────────────────────

export const exportToPDF = async (reportData, monthLabel, pdfTemplateRef) => {
  const { summary, categoryBreakdown, dailyAnalysis, pendingAnalysis, insights, monthExpenses } = reportData;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = 210;
  const pageH = 297;
  const margin = 14;
  const contentW = pageW - margin * 2;

  const generatedDate = format(new Date(), 'dd MMM yyyy, hh:mm a');

  // ── Draw header banner ──────────────────────────────────────────────────
  const drawHeader = (pageNum) => {
    // Purple gradient background banner
    roundedRect(doc, 0, 0, pageW, 38, 0, COLORS.purple);
    doc.setFillColor(...COLORS.blue);
    doc.rect(pageW - 60, 0, 60, 38, 'F');

    // Logo circle
    doc.setFillColor(255, 255, 255, 0.15);
    doc.circle(margin + 7, 19, 7, 'F');
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('₹', margin + 4.5, 22.5);

    // Brand name
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.white);
    doc.text('Paisa Tracker', margin + 17, 17);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(200, 200, 255);
    doc.text('Monthly Financial Report', margin + 17, 24);

    // Right side: month + page
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.white);
    doc.text(monthLabel, pageW - margin, 17, { align: 'right' });
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(200, 200, 255);
    doc.text(`Page ${pageNum}`, pageW - margin, 24, { align: 'right' });
  };

  // ── Draw footer ─────────────────────────────────────────────────────────
  const drawFooter = () => {
    doc.setDrawColor(...COLORS.border);
    doc.line(margin, pageH - 12, pageW - margin, pageH - 12);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.textDisabled);
    doc.text(`Generated by Paisa Tracker  ·  ${generatedDate}`, margin, pageH - 7);
    doc.text('Confidential — For personal use only', pageW - margin, pageH - 7, { align: 'right' });
  };

  // ── Draw a stat card ────────────────────────────────────────────────────
  const drawStatCard = (x, y, w, h, label, value, color) => {
    roundedRect(doc, x, y, w, h, 3, COLORS.elevated, COLORS.border);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.textMuted);
    doc.text(label, x + w / 2, y + 8, { align: 'center' });
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...color);
    doc.text(value, x + w / 2, y + 16, { align: 'center' });
  };

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Summary
  // ══════════════════════════════════════════════════════════════════════════
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, pageW, pageH, 'F');
  drawHeader(1);

  let y = 48;

  // Section title
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text('Financial Summary', margin, y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.textMuted);
  doc.text(monthLabel, margin, y + 6);

  y += 14;

  // 4 stat cards in a row
  const cardW = (contentW - 6) / 4;
  const cardH = 24;
  const cards = [
    { label: 'TOTAL SPENT', value: INR(summary.totalSpent), color: COLORS.red },
    { label: 'TRANSACTIONS', value: String(summary.txCount), color: COLORS.blue },
    { label: 'SHOP PENDING', value: INR(summary.pendingShop), color: COLORS.yellow },
    { label: 'FRIEND PENDING', value: INR(summary.pendingFriend), color: COLORS.purple },
  ];

  cards.forEach((card, i) => {
    drawStatCard(margin + i * (cardW + 2), y, cardW, cardH, card.label, card.value, card.color);
  });

  y += cardH + 10;

  // Category breakdown table
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text('Category Breakdown', margin, y);
  y += 8;

  // Table header
  roundedRect(doc, margin, y, contentW, 8, 2, COLORS.elevated);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textMuted);
  doc.text('CATEGORY', margin + 4, y + 5.5);
  doc.text('AMOUNT', margin + contentW * 0.5, y + 5.5);
  doc.text('%', margin + contentW * 0.75, y + 5.5);
  doc.text('BAR', margin + contentW * 0.85, y + 5.5);
  y += 10;

  const catColors = [COLORS.purple, COLORS.blue, COLORS.green, COLORS.yellow, COLORS.red, [236,72,153], [99,102,241], COLORS.textMuted];
  categoryBreakdown.forEach((cat, i) => {
    const rowBg = i % 2 === 0 ? COLORS.card : COLORS.bg;
    roundedRect(doc, margin, y - 1, contentW, 8, 1, rowBg);
    doc.setTextColor(...COLORS.textPrimary);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`${cat.emoji} ${cat.label}`, margin + 4, y + 4.5);
    doc.text(INR(cat.amount), margin + contentW * 0.5, y + 4.5);
    doc.text(`${cat.pct}%`, margin + contentW * 0.75, y + 4.5);
    // Progress bar
    const barW = contentW * 0.12;
    const barX = margin + contentW * 0.85;
    doc.setFillColor(...COLORS.elevated);
    doc.roundedRect(barX, y + 1.5, barW, 4, 1, 1, 'F');
    const fillW = (cat.pct / 100) * barW;
    if (fillW > 0) {
      doc.setFillColor(...(catColors[i % catColors.length]));
      doc.roundedRect(barX, y + 1.5, fillW, 4, 1, 1, 'F');
    }
    y += 9;
  });

  y += 6;

  // Daily analysis summary
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text('Daily Analysis', margin, y);
  y += 8;

  const dailyCards = [
    { label: 'Avg Daily Spend', value: INR(dailyAnalysis.avgDaily), color: COLORS.blue },
    { label: 'No-Spend Days', value: String(dailyAnalysis.noSpendDays), color: COLORS.green },
    {
      label: 'Highest Day',
      value: dailyAnalysis.highestDay ? `${dailyAnalysis.highestDay.dayLabel?.split(',')[0] || '-'}  ${INR(dailyAnalysis.highestDay.amount)}` : 'N/A',
      color: COLORS.yellow,
    },
    { label: 'Weekend Spend', value: INR(dailyAnalysis.weekendSpend), color: COLORS.red },
  ];

  const dCardW = (contentW - 6) / 4;
  dailyCards.forEach((card, i) => {
    drawStatCard(margin + i * (dCardW + 2), y, dCardW, 24, card.label, card.value, card.color);
  });

  y += 34;

  // Try to capture charts from the DOM if ref exists
  if (pdfTemplateRef?.current) {
    try {
      const canvas = await html2canvas(pdfTemplateRef.current, {
        scale: 1.5,
        backgroundColor: '#0A0A0F',
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL('image/jpeg', 0.85);
      const imgW = contentW;
      const imgH = (canvas.height / canvas.width) * contentW;

      if (y + imgH < pageH - 20) {
        doc.addImage(imgData, 'JPEG', margin, y, imgW, Math.min(imgH, 100));
      } else {
        doc.addPage();
        doc.setFillColor(...COLORS.bg);
        doc.rect(0, 0, pageW, pageH, 'F');
        drawHeader(2);
        doc.addImage(imgData, 'JPEG', margin, 48, imgW, Math.min(imgH, 210));
        drawFooter();
      }
    } catch (e) {
      console.warn('Chart capture failed:', e);
    }
  }

  drawFooter();

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — Smart Insights + Pending
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, pageW, pageH, 'F');
  drawHeader(2);

  y = 48;

  // Insights
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text('Smart Financial Insights', margin, y);
  y += 10;

  const typeColors = { warning: COLORS.yellow, positive: COLORS.green, info: COLORS.blue };
  insights.slice(0, 7).forEach((ins) => {
    const c = typeColors[ins.type] || COLORS.blue;
    roundedRect(doc, margin, y - 1, contentW, ins.detail ? 16 : 12, 3, COLORS.card, COLORS.border);
    doc.setFillColor(...c);
    doc.rect(margin, y - 1, 2.5, ins.detail ? 16 : 12, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.textPrimary);
    doc.text(`${ins.icon}  ${ins.text}`, margin + 6, y + 5);
    if (ins.detail) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.textMuted);
      doc.text(ins.detail, margin + 6, y + 11);
    }
    y += (ins.detail ? 16 : 12) + 3;
  });

  y += 6;

  // Pending Analysis
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text('Pending Money Analysis', margin, y);
  y += 8;

  // Friends pending
  if (pendingAnalysis.friendBreakdown.length > 0) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.textMuted);
    doc.text('FRIENDS', margin, y);
    y += 6;

    pendingAnalysis.friendBreakdown.forEach((f, i) => {
      roundedRect(doc, margin, y - 1, contentW, 10, 2, i % 2 === 0 ? COLORS.card : COLORS.bg);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.textPrimary);
      doc.text(`👤  ${f.name}`, margin + 4, y + 5.5);
      doc.setTextColor(...COLORS.yellow);
      doc.text(`Pending: ${INR(f.pending)}`, margin + 80, y + 5.5);
      doc.setTextColor(...COLORS.green);
      doc.text(`Received: ${INR(f.received)}`, margin + 130, y + 5.5);
      y += 11;
    });
    y += 4;
  }

  // Shop pending
  if (pendingAnalysis.shopPending.length > 0) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.textMuted);
    doc.text('SHOP PENDING', margin, y);
    y += 6;

    pendingAnalysis.shopPending.slice(0, 10).forEach((s, i) => {
      roundedRect(doc, margin, y - 1, contentW, 10, 2, i % 2 === 0 ? COLORS.card : COLORS.bg);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.textPrimary);
      doc.text(`🏪  ${s.shopName || s.name || 'Shop'}`, margin + 4, y + 5.5);
      doc.setTextColor(...COLORS.yellow);
      doc.text(INR(s.amount), pageW - margin, y + 5.5, { align: 'right' });
      y += 11;
    });
  }

  drawFooter();

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 3 — Transaction History
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, pageW, pageH, 'F');
  drawHeader(3);

  y = 48;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textPrimary);
  doc.text(`Transaction History (${monthExpenses.length} transactions)`, margin, y);
  y += 10;

  // Table header
  roundedRect(doc, margin, y, contentW, 8, 2, COLORS.elevated);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.textMuted);
  doc.text('DATE', margin + 4, y + 5.5);
  doc.text('CATEGORY', margin + 35, y + 5.5);
  doc.text('NOTES', margin + 80, y + 5.5);
  doc.text('AMOUNT', pageW - margin - 4, y + 5.5, { align: 'right' });
  y += 10;

  monthExpenses.forEach((tx, i) => {
    if (y > pageH - 20) {
      drawFooter();
      doc.addPage();
      doc.setFillColor(...COLORS.bg);
      doc.rect(0, 0, pageW, pageH, 'F');
      drawHeader(4);
      y = 48;
    }
    const rowBg = i % 2 === 0 ? COLORS.card : COLORS.bg;
    roundedRect(doc, margin, y - 1, contentW, 9, 1, rowBg);
    const dateStr = tx.date || tx.createdAt;
    let displayDate = '';
    try { displayDate = format(new Date(dateStr), 'dd MMM'); } catch { displayDate = '-'; }
    // Category info is used for display in the row below
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.textPrimary);
    doc.text(displayDate, margin + 4, y + 5);
    doc.text(tx.category || 'Other', margin + 35, y + 5);
    const note = (tx.notes || tx.description || tx.note || '').slice(0, 30);
    doc.setTextColor(...COLORS.textMuted);
    doc.text(note, margin + 80, y + 5);
    doc.setTextColor(...COLORS.red);
    doc.text(INR(tx.amount), pageW - margin - 4, y + 5, { align: 'right' });
    y += 10;
  });

  drawFooter();

  // Save
  const filename = `Paisa_Tracker_${monthLabel.replace(' ', '_')}_Report.pdf`;
  doc.save(filename);
  return filename;
};

// ─── EXCEL EXPORT ─────────────────────────────────────────────────────────────

export const exportToExcel = (reportData, monthLabel) => {
  const { summary, categoryBreakdown, monthExpenses, pendingAnalysis } = reportData;
  const wb = XLSX.utils.book_new();

  // ── Sheet 1: Monthly Summary ─────────────────────────────────────────────
  const summaryRows = [
    ['Paisa Tracker — Monthly Financial Report'],
    [`Month: ${monthLabel}`],
    [`Generated: ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`],
    [],
    ['FINANCIAL SUMMARY'],
    ['Metric', 'Value'],
    ['Total Spent', summary.totalSpent],
    ['Total Transactions', summary.txCount],
    ['Shop Pending', summary.pendingShop],
    ['Friend Pending', summary.pendingFriend],
    ['Total Pending', summary.totalPending],
    ['Shop Received', summary.receivedShop],
    ['Friend Received', summary.receivedFriend],
    [],
    ['CATEGORY BREAKDOWN'],
    ['Category', 'Amount (₹)', 'Percentage (%)'],
    ...categoryBreakdown.map((c) => [c.label, c.amount, c.pct]),
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(summaryRows);
  ws1['!cols'] = [{ wch: 30 }, { wch: 20 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, ws1, 'Monthly Summary');

  // ── Sheet 2: Expense Transactions ────────────────────────────────────────
  const txHeaders = ['Date', 'Category', 'Notes', 'Amount (₹)', 'Transaction ID'];
  const txRows = monthExpenses.map((e) => {
    let dateStr = '-';
    try { dateStr = format(new Date(e.date || e.createdAt), 'dd MMM yyyy'); } catch {}
    return [
      dateStr,
      e.category || 'Other',
      e.notes || e.description || e.note || '',
      Number(e.amount),
      e.id || '',
    ];
  });
  const ws2 = XLSX.utils.aoa_to_sheet([txHeaders, ...txRows]);
  ws2['!cols'] = [{ wch: 15 }, { wch: 15 }, { wch: 30 }, { wch: 15 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(wb, ws2, 'Expense Transactions');

  // ── Sheet 3: Friends Pending ─────────────────────────────────────────────
  const friendHeaders = ['Friend Name', 'Pending (₹)', 'Received (₹)', 'Net (₹)'];
  const friendRows = pendingAnalysis.friendBreakdown.map((f) => [
    f.name,
    f.pending,
    f.received,
    f.pending - f.received,
  ]);
  const ws3 = XLSX.utils.aoa_to_sheet([
    ['Friends Pending Money'],
    [`Total Pending: ₹${pendingAnalysis.friendPendingTotal.toLocaleString('en-IN')}`],
    [`Recovery Rate: ${pendingAnalysis.friendRecoveryRate}%`],
    [],
    friendHeaders,
    ...friendRows,
  ]);
  ws3['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 15 }, { wch: 15 }];
  XLSX.utils.book_append_sheet(wb, ws3, 'Friends Pending');

  // ── Sheet 4: Shop Pending ────────────────────────────────────────────────
  const shopHeaders = ['Shop Name', 'Amount (₹)', 'Status', 'Date'];
  const shopRows = [
    ...pendingAnalysis.shopPending.map((s) => {
      let dateStr = '-';
      try { dateStr = format(new Date(s.createdAt), 'dd MMM yyyy'); } catch {}
      return [s.shopName || s.name || 'Shop', Number(s.amount), 'Pending', dateStr];
    }),
    ...pendingAnalysis.shopReceived.map((s) => {
      let dateStr = '-';
      try { dateStr = format(new Date(s.receivedAt || s.createdAt), 'dd MMM yyyy'); } catch {}
      return [s.shopName || s.name || 'Shop', Number(s.amount), 'Received', dateStr];
    }),
  ];
  const ws4 = XLSX.utils.aoa_to_sheet([
    ['Shop Pending Money'],
    [`Total Pending: ₹${pendingAnalysis.shopPendingTotal.toLocaleString('en-IN')}`],
    [],
    shopHeaders,
    ...shopRows,
  ]);
  ws4['!cols'] = [{ wch: 25 }, { wch: 15 }, { wch: 12 }, { wch: 15 }];
  XLSX.utils.book_append_sheet(wb, ws4, 'Shop Pending');

  // Save
  const filename = `Paisa_Tracker_${monthLabel.replace(' ', '_')}_Report.xlsx`;
  XLSX.writeFile(wb, filename);
  return filename;
};
